<?php

declare(strict_types=1);

// Each entry here is untrusted input from ScriptRegistry's point of view — see
// App\Scripts\ScriptDefinition::fromArray() for the validation boundary. Field
// shapes are transcribed from each script's own `--help` output, not guessed.

return [
    [
        'slug' => 'ebay.export-listings',
        'category' => 'aspects',
        'title' => 'Export Listings (roster)',
        'description' => 'Step 1 of Aspects: enumerates every active listing for an account (item ID, SKU, price, variations) from eBay\'s Sell Feed API and writes listings.json. This is the roster every later aspects step reads from.',
        'usage_notes' => 'Run this first for a new account, or whenever you need to pick up newly-listed/ended items. Read-only against eBay — it creates a report request, it never modifies a listing.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/export_listings.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 1,
        'output_files' => [
            'marketplaces/ebay/data/{account}/output/listings.json',
            'marketplaces/ebay/data/{account}/output/skus.csv',
        ],
        'creates' => [
            [
                'file' => 'skus.csv',
                'columns' => ['item_id', 'sku', 'is_variation', 'price', 'quantity', 'variation_specifics'],
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'format',
                'flag' => '--format',
                'type' => 'enum',
                'required' => false,
                'options' => ['FIXED_PRICE', 'AUCTION'],
                'help' => 'Limit to one listing format. Leave blank for both.',
            ],
            [
                'name' => 'task',
                'flag' => '--task',
                'type' => 'string',
                'required' => false,
                'help' => 'Resume an existing report task ID instead of creating a new one — only needed if a previous run timed out waiting.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.enrich-listings',
        'category' => 'aspects',
        'title' => 'Enrich Listings (pull aspects)',
        'description' => 'Step 2 of Aspects: fetches live item specifics (aspects) for an account via the eBay Browse API and writes items/{itemId}.json snapshots.',
        'usage_notes' => 'Use --refresh to force a re-fetch instead of using cached snapshots. Requires listings.json — run Export Listings first if this errors that the roster is missing.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/enrich_listings.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 2,
        'output_files' => [
            'marketplaces/ebay/data/{account}/output/enriched_summary.csv',
            'marketplaces/ebay/data/{account}/output/category_coverage.csv',
        ],
        'creates' => [
            [
                'file' => 'enriched_summary.csv',
                'columns' => ['item_id', 'title', 'category_id', 'category_path', 'aspect_count', 'status'],
            ],
            [
                'file' => 'category_coverage.csv',
                'columns' => ['category_id', 'category_path', 'listing_count'],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/listings.json',
                'label' => 'Listings roster — the item IDs this pulls aspects for. Produced by Export Listings; if this is missing, that script needs to run first.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'ids',
                'flag' => '--ids',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated item IDs to limit the run to. Leave blank for the full account.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Cap the number of listings processed.',
            ],
            [
                'name' => 'refresh',
                'flag' => '--refresh',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Force re-fetch even if a cached snapshot already exists.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.build-review-sheet',
        'category' => 'aspects',
        'title' => 'Read Aspects (build worksheet)',
        'description' => 'Step 6 of Aspects: assembles review_sheet.csv from the data pulled in steps 1-5 (roster, current aspects, category schema, gap audit, deterministic fills) — one row per listing per aspect. This is the read script: choose read for just what\'s live on eBay right now, or worksheet for a full reviewer sheet with proposed values and blank columns to fill in.',
        'usage_notes' => 'read: current_value only, no proposed/blank columns — a quick export of what\'s actually live. worksheet: also includes proposed_value (from Fill Aspects\' deterministic proposals, blank if none exist yet) and blank approved_value/reviewer_notes columns — this is what you hand to someone for review. Rerunning this REPLACES review_sheet.csv entirely, including any approved_value a reviewer already filled in — do not rerun this after a review round has started without backing up the file first.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/build_review_sheet.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 6,
        'output_files' => ['marketplaces/ebay/data/{account}/output/review_sheet.csv'],
        'creates' => [
            [
                'file' => 'review_sheet.csv',
                'columns' => [
                    'item_id', 'sku', 'varied_by', 'name', 'category_id', 'aspect', 'mode',
                    'cardinality', 'source', 'certainty', 'current_value', 'proposed_value',
                    'approved_value', 'reviewer_notes', 'allowed_values', 'title',
                ],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/listings.json',
                'label' => 'Listings roster — every listing this walks. Produced by Export Listings.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'mode',
                'flag' => '--mode',
                'type' => 'enum',
                'required' => true,
                'options' => ['read', 'worksheet'],
                'help' => 'read: just what\'s live on eBay right now. worksheet: also includes proposed values and blank columns for a reviewer to fill in — pick this if you\'re about to hand the sheet to someone for review.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.apply-aspects',
        'category' => 'aspects',
        'title' => 'Apply Aspects (live write)',
        'description' => 'Writes approved item-specifics changes from review_sheet.csv live to eBay via ReviseItem.',
        'usage_notes' => 'Use item, items, or offset+limit to narrow the run — leave all three blank to target every eligible item in the account (still gated by --confirm=WRITE for a bulk live run). Dry-run by default; --verify round-trips through eBay without committing; --live actually writes.',
        'type' => 'write',
        'cli_path' => 'marketplaces/ebay/scripts/apply_aspects.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 12,
        'output_files' => ['marketplaces/ebay/data/{account}/output/apply_aspects_run.csv'],
        'creates' => [
            [
                'file' => 'apply_aspects_run.csv',
                'columns' => ['timestamp', 'item_id', 'verify_only', 'ack', 'errors'],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/apply_set.json',
                'label' => 'Apply Set — the exact, complete specifics payload this will push. Produced by Build Apply Set; regenerate that first if you\'ve changed anything.',
            ],
            [
                'path' => 'marketplaces/ebay/data/{account}/output/review_sheet.csv',
                'label' => 'Review Sheet — source for the unchanged variation-child values sent alongside a variation listing\'s parent specifics.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'item',
                'flag' => '--item',
                'type' => 'string',
                'required' => false,
                'help' => 'A single item ID to run against.',
            ],
            [
                'name' => 'items',
                'flag' => '--items',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated item IDs to run against.',
            ],
            [
                'name' => 'offset',
                'flag' => '--offset',
                'type' => 'int',
                'required' => false,
                'help' => 'Skip this many affected items before starting (paired with limit).',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Process at most this many affected items (paired with offset).',
            ],
            [
                'name' => 'exclude',
                'flag' => '--exclude',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated item IDs to skip.',
            ],
            [
                'name' => 'verify',
                'flag' => '--verify',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Round-trip through eBay to validate the payload without committing.',
            ],
            [
                'name' => 'live',
                'flag' => '--live',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to eBay.',
            ],
            [
                'name' => 'confirm',
                'flag' => '--confirm',
                'type' => 'string',
                'required' => false,
                'help' => 'Must be exactly WRITE for a bulk (more than one item) live run.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.author-descriptions-ai',
        'category' => 'descriptions',
        'title' => 'Author Descriptions (AI)',
        'description' => 'Step 3 of Descriptions: calls the Anthropic API directly to write the six AUTHOR_PROMPT.md fields (factual/sales/bullets/mobile/title_issue/new_title) per listing, upserting into desc_authored.jsonl. Never touches eBay — writes local files only.',
        'usage_notes' => 'This calls a paid API — real cost per run, printed at the end. Always run --dry-run first to see the chunk plan and an example prompt at no cost. Skips item_ids already in desc_authored.jsonl unless --ids is given. Requires desc_source_pack.jsonl — run Extract Description Source first if this errors that the grounding pack is missing.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/author_descriptions_ai.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 3,
        'output_files' => ['marketplaces/ebay/data/{account}/output/author_descriptions_ai_errors.csv'],
        'creates' => [
            [
                'file' => 'author_descriptions_ai_errors.csv',
                'columns' => ['item_id', 'reason', 'raw'],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/desc_source_pack.jsonl',
                'label' => 'Description Source Pack — the per-listing source content (title, feature bullets, aspects) this authors from.',
            ],
            [
                'path' => 'marketplaces/ebay/data/{account}/output/desc_authored.jsonl',
                'label' => 'Already-authored descriptions — item_ids already in here are skipped by default (resumability). Use --ids to reprocess a specific one anyway.',
            ],
            [
                'path' => 'marketplaces/ebay/scripts/AUTHOR_PROMPT.md',
                'label' => 'The exact prompt spec this sends to the API — the actual rules the AI is asked to follow.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'ids',
                'flag' => '--ids',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated item IDs to (re-)author regardless of whether already in desc_authored.jsonl. Leave blank to process unauthored listings only.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Cap how many listings to process.',
            ],
            [
                'name' => 'chunk-size',
                'flag' => '--chunk-size',
                'type' => 'int',
                'required' => false,
                'default' => 5,
                'help' => 'Listings per API call. Default 5.',
            ],
            [
                'name' => 'model',
                'flag' => '--model',
                'type' => 'enum',
                'required' => false,
                'default' => 'claude-sonnet-4-6',
                'options' => ['claude-haiku-4-5', 'claude-sonnet-4-6', 'claude-opus-4-8'],
                'help' => 'Default claude-sonnet-4-6.',
            ],
            [
                'name' => 'dry-run',
                'flag' => '--dry-run',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Show the chunk plan and one example prompt. No API calls, no cost, no writes.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.audit-media',
        'category' => 'descriptions',
        'title' => 'Audit Media (source snapshot)',
        'description' => 'Step 1 of Descriptions: pulls each listing\'s current live description HTML, price, and gallery image URLs (with EPS/self-hosted + resolution flags) from eBay\'s Browse API into media/{itemId}.json. Nothing here is invented — this is the raw material every later description step reads from.',
        'usage_notes' => 'Read-only against eBay. Run this first for an account, or whenever you want a fresh snapshot of what\'s actually live before re-authoring. --refresh forces re-pulling listings already snapshotted.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/audit_media.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 1,
        'output_files' => [
            'marketplaces/ebay/data/{account}/output/media_summary.csv',
            'marketplaces/ebay/data/{account}/output/media_images.csv',
        ],
        'creates' => [
            [
                'file' => 'media_summary.csv',
                'columns' => [
                    'item_id', 'row_type', 'sku', 'child_item_id', 'match_method', 'title',
                    'image_url', 'image_count', 'unique_images', 'shared_with_parent_images',
                    'eps_images', 'non_eps_images', 'all_eps', 'min_long_px', 'max_long_px',
                    'below_zoom_800', 'below_ideal', 'desc_html_len', 'desc_text_len', 'has_desc',
                    'is_group', 'variation_count', 'parent_image_count', 'child_image_count_total',
                ],
            ],
            [
                'file' => 'media_images.csv',
                'columns' => ['item_id', 'position', 'url', 'width', 'height', 'host', 'is_eps'],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/listings.json',
                'label' => 'Listings roster — every listing this walks. Produced by Export Listings.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Cap how many listings to process — useful as a quick canary run.',
            ],
            [
                'name' => 'ids',
                'flag' => '--ids',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated item IDs to snapshot instead of the full roster.',
            ],
            [
                'name' => 'refresh',
                'flag' => '--refresh',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Re-pull listings that already have a media/ snapshot instead of skipping them.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.extract-description-source',
        'category' => 'descriptions',
        'title' => 'Extract Description Source (source content pack)',
        'description' => 'Step 2 of Descriptions: builds the per-listing grounding pack an authoring pass may only add to, never invent beyond — title, price, aspects, short description, narrative paragraphs, and feature bullets, pulled from Audit Media\'s snapshots (and Build Apply Set\'s merged aspects when available).',
        'usage_notes' => 'Local-file-only, no eBay calls. Always processes BOTH dows and ige in one run — there is no --account flag. Requires Audit Media\'s media/ snapshots to already exist for an account, or that account is silently skipped. Writes marketplaces/ebay/data/dows/output/desc_source_pack.jsonl and marketplaces/ebay/data/ige/output/desc_source_pack.jsonl directly — not downloadable from this run\'s page since both accounts share the same filename.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/extract_description_source.py',
        'interpreter' => 'python3',
        'featured' => true,
        'step' => 2,
        'output_files' => [],
        'params' => [],
    ],
    [
        'slug' => 'ebay.build-description-review',
        'category' => 'descriptions',
        'title' => 'Build Description Review',
        'description' => 'Step 4 of Descriptions: renders the standardized description template (factual paragraph, sales pitch, key features, product specs, mobile summary) from Author Descriptions (AI)\'s output and assembles description_review.csv — old vs. new for every field, plus the full rendered HTML per listing. This is the sheet you hand to a reviewer.',
        'usage_notes' => 'Rerunning this REPLACES description_review.csv entirely, including any approved/reviewer_notes a reviewer already filled in — back up the file first if a review round has started. Requires desc_source_pack.jsonl (Extract Description Source) to exist for the account.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/build_description_review.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 4,
        'output_files' => ['marketplaces/ebay/data/{account}/output/description_review.csv'],
        'creates' => [
            [
                'file' => 'description_review.csv',
                'columns' => [
                    'item_id', 'sku', 'old_first_description', 'new_first_description',
                    'old_sales_description', 'new_sales_description', 'old_title', 'new_title',
                    'price', 'old_key_features', 'new_key_features', 'old_mobile_text',
                    'new_mobile_text', 'old_description', 'new_description', 'prev_html',
                    'new_html', 'what_changed', 'approved', 'reviewer_notes', 'mpn', 'upc',
                    'specs/values',
                ],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/desc_source_pack.jsonl',
                'label' => 'Grounding pack — the per-listing source content this renders from. Produced by Extract Description Source.',
            ],
            [
                'path' => 'marketplaces/ebay/data/{account}/output/desc_authored.jsonl',
                'label' => 'Authored answers — the factual/sales/bullets/mobile/title fields. Produced by Author Descriptions (AI).',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.find-mobile-desc-mismatch',
        'category' => 'descriptions',
        'title' => 'Find Mobile Description Mismatch',
        'description' => 'Step 5 of Descriptions: flags listings where eBay\'s hidden mobile summary doesn\'t actually match the visible description body — a real, separately-found bug class on other listings earlier in this project.',
        'usage_notes' => 'Local-file-only, reads Audit Media\'s media/ snapshots for BOTH accounts in one run — there is no --account flag. Run Audit Media for an account first or it contributes nothing to the output.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/find_mobile_desc_mismatch.py',
        'interpreter' => 'python3',
        'featured' => false,
        'step' => 5,
        'optional' => true,
        'output_files' => ['marketplaces/ebay/data/mobile_vs_desc_match.csv'],
        'creates' => [
            [
                'file' => 'mobile_vs_desc_match.csv',
                'columns' => [
                    'account', 'item_id', 'sku', 'title', 'status', 'match_pct', 'mobile_words',
                    'visible_words', 'mobile_words_missing_from_visible', 'mobile_text', 'visible_text',
                ],
            ],
        ],
        'params' => [
            [
                'name' => 'threshold',
                'flag' => '--threshold',
                'type' => 'int',
                'required' => false,
                'default' => 95,
                'help' => 'Minimum visible-body word-containment percent to count as a match. Default 95 — listings scoring below this are flagged MISMATCH.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.build-mobile-fix-review',
        'category' => 'descriptions',
        'title' => 'Build Mobile Fix Review',
        'description' => 'Step 6 of Descriptions: before/after sheet for the listings Find Mobile Description Mismatch flagged as MISMATCH or NO_MOBILE, reusing Build Description Review\'s already-rendered fix (its mobile summary is derived from the same intro, so it fixes the mismatch automatically).',
        'usage_notes' => 'Local-file-only. Also stamps the previous mobile-state into description_review.csv\'s reviewer_notes column for the affected rows (for BOTH accounts) — a backup is kept, but this does mutate that file as a side effect, not just read it. Requires Find Mobile Description Mismatch to have run first.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/build_mobile_fix_review.py',
        'interpreter' => 'python3',
        'featured' => false,
        'step' => 6,
        'optional' => true,
        'output_files' => ['marketplaces/ebay/data/mobile_desc_fix_review.csv'],
        'creates' => [
            [
                'file' => 'mobile_desc_fix_review.csv',
                'columns' => [
                    'account', 'item_id', 'sku', 'title', 'mobile_status', 'match_pct',
                    'before_mobile_text', 'after_mobile_text', 'before_visible_text',
                    'after_description', 'before_html', 'after_html', 'reviewer_notes', 'approved',
                ],
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'ebay.apply-descriptions',
        'category' => 'descriptions',
        'title' => 'Apply Descriptions (live write)',
        'description' => 'Step 7 of Descriptions: writes reviewed description/title changes from description_review.csv live to eBay via ReviseItem. No re-authoring, no LLM calls — this only pushes what Build Description Review already computed.',
        'usage_notes' => 'Only writes rows where the \'approved\' column is a truthy marker (yes/y/true/1/approved/approve) — this is the reviewer\'s decision column; nothing writes until a row is marked approved. Use item, items, or offset+limit to narrow the run — leave all three blank to target every approved item in the account (still gated by --confirm=WRITE for a bulk live run). Dry-run by default; --verify round-trips through eBay without committing; --live actually writes.',
        'type' => 'write',
        'cli_path' => 'marketplaces/ebay/scripts/apply_descriptions.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 7,
        'output_files' => ['marketplaces/ebay/data/{account}/output/apply_descriptions_run.csv'],
        'creates' => [
            [
                'file' => 'apply_descriptions_run.csv',
                'columns' => ['timestamp', 'item_id', 'verify_only', 'ack', 'errors', 'title_changed'],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/description_review.csv',
                'label' => 'Review Sheet — source for old/new HTML and title, and the approved column this gates on. Produced by Build Description Review.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'item',
                'flag' => '--item',
                'type' => 'string',
                'required' => false,
                'help' => 'A single item ID to run against.',
            ],
            [
                'name' => 'items',
                'flag' => '--items',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated item IDs to run against.',
            ],
            [
                'name' => 'offset',
                'flag' => '--offset',
                'type' => 'int',
                'required' => false,
                'help' => 'Skip this many approved items before starting (paired with limit).',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Process at most this many approved items (paired with offset).',
            ],
            [
                'name' => 'exclude',
                'flag' => '--exclude',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated item IDs to skip.',
            ],
            [
                'name' => 'verify',
                'flag' => '--verify',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Round-trip through eBay to validate the payload without committing.',
            ],
            [
                'name' => 'live',
                'flag' => '--live',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to eBay.',
            ],
            [
                'name' => 'confirm',
                'flag' => '--confirm',
                'type' => 'string',
                'required' => false,
                'help' => 'Must be exactly WRITE for a bulk (more than one item) live run.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.analyze-descriptions',
        'category' => 'descriptions',
        'title' => 'Analyze Descriptions (SEO score)',
        'description' => 'Scores each listing\'s CURRENT eBay description for SEO quality — word count, title/aspect keyword coverage, bullet/heading/schema structure, duplicate content — so you know what needs rewriting and can prioritize. Pure analysis, no eBay writes.',
        'usage_notes' => 'Standalone — not a required step in the main pipeline, run any time after Audit Media to see where an account stands today. Requires Audit Media\'s media/ snapshots to exist for the account.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/analyze_descriptions.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'output_files' => ['marketplaces/ebay/data/{account}/output/description_audit.csv'],
        'creates' => [
            [
                'file' => 'description_audit.csv',
                'columns' => [
                    'item_id', 'sku', 'title', 'price', 'score', 'treatment', 'word_count',
                    'title_coverage_pct', 'aspect_hits', 'aspect_total', 'has_bullets', 'has_heading',
                    'has_schema', 'keyword_in_intro', 'is_duplicate', 'dup_group_size', 'issues',
                ],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/media/',
                'label' => 'Media snapshots — the current live description HTML this scores. Produced by Audit Media; contributes nothing for this account if that hasn\'t run yet.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.audit-description-images',
        'category' => 'descriptions',
        'title' => 'Audit Description Images',
        'description' => 'Checks <img> tags embedded directly in each listing\'s description HTML (mostly old AWS-hosted product photos) for broken links and missing/generic-placeholder alt text. A different concern from the gallery/EPS image audit — this is images hard-coded into the description body itself.',
        'usage_notes' => 'Standalone — not a required step in the main pipeline. Requires Audit Media\'s media/ snapshots to exist for the account; reads description HTML already captured there, makes no eBay API calls itself (only HTTP HEAD/GET requests to the image URLs found).',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/audit_description_images.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'output_files' => ['marketplaces/ebay/data/{account}/output/description_image_audit.csv'],
        'creates' => [
            [
                'file' => 'description_image_audit.csv',
                'columns' => ['item_id', 'position', 'src', 'alt', 'alt_status', 'http_status', 'broken'],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/media/',
                'label' => 'Media snapshots — the description HTML this scans for <img> tags. Produced by Audit Media; contributes nothing for this account if that hasn\'t run yet.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Cap how many listings to check.',
            ],
            [
                'name' => 'concurrency',
                'flag' => '--concurrency',
                'type' => 'int',
                'required' => false,
                'default' => 20,
                'help' => 'Parallel HTTP checks in flight. Default 20.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.merge-handoff-approvals',
        'category' => 'aspects',
        'title' => 'Merge Approved Changes (from CSV)',
        'description' => 'Step 8 of Aspects: folds a CSV of reviewed aspect values into review_sheet.csv\'s approved_value column — the step after a human has reviewed the worksheet, before normalizing units, Build Apply Set, and Apply Aspects. Never touches eBay directly, and never touches any review_sheet.csv column but approved_value.',
        'usage_notes' => 'Required CSV columns: item_id, sku, aspect, final_value (optional: unit_normalized). One row per (item_id, sku, aspect) you want to set. Leave final_value blank to skip that row, or set it to the literal text "blank_value" to explicitly clear a currently-live aspect. review_sheet.csv is backed up automatically before writing (first run only — the backup is never overwritten).',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/merge_handoff_approvals.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 8,
        'optional' => true,
        'output_files' => ['marketplaces/ebay/data/{account}/output/handoff_round1_applied.csv'],
        'creates' => [
            [
                'file' => 'handoff_round1_applied.csv',
                'columns' => [
                    'item_id', 'sku', 'aspect', 'source', 'prior_approved_value', 'final_value_in',
                    'applied_approved_value', 'action',
                ],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/review_sheet.csv',
                'label' => 'Review Sheet — the table your CSV rows are matched against and merged into. Your upload\'s (item_id, sku, aspect) combination must already exist as a row here, or it\'s logged as unmatched-skipped.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'input',
                'flag' => '--input',
                'type' => 'file',
                'required' => true,
                'help' => 'CSV columns required: item_id, sku, aspect, final_value (optional: unit_normalized). One row per (item_id, sku, aspect) to set. Blank final_value = skip that row; the literal text "blank_value" = explicitly clear a currently-live aspect.',
            ],
            [
                'name' => 'dry-run',
                'flag' => '--dry-run',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Preview the merge decisions without writing review_sheet.csv.',
            ],
            [
                'name' => 'force',
                'flag' => '--force',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Overwrite an existing approved_value that conflicts with the CSV\'s value (default: conflicts are skipped and logged, not overwritten).',
            ],
        ],
    ],
    [
        'slug' => 'ebay.build-apply-set',
        'category' => 'aspects',
        'title' => 'Build Apply Set (finalize aspect payload)',
        'description' => 'Step 10 of Aspects: collapses review_sheet.csv into the complete, safe specifics payload Apply Aspects will send — merges kept current aspects, approved corrections, and new fills, minus explicit deletions. Dry-run only: no eBay calls.',
        'usage_notes' => 'Run this after Merge Approved Changes and unit normalization, before Apply Aspects (live write).',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/build_apply_set.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 10,
        'output_files' => [
            'marketplaces/ebay/data/{account}/output/apply_set.json',
            'marketplaces/ebay/data/{account}/output/apply_preview.csv',
        ],
        'creates' => [
            [
                'file' => 'apply_preview.csv',
                'columns' => [
                    'item_id', 'sku', 'aspect', 'action', 'final_value', 'from_value',
                    'chosen_from', 'mode', 'valid', 'title',
                ],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/review_sheet.csv',
                'label' => 'Review Sheet — this is what gets collapsed into apply_set.json. Run Merge Approved Changes first if you have a CSV of updates to fold in.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'threshold',
                'flag' => '--threshold',
                'type' => 'int',
                'required' => false,
                'default' => 80,
                'help' => 'Minimum certainty (0-100) for an unreviewed LLM fill to be applied. Deterministic fills and human approvals always apply regardless. Default 80.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.fetch-category-aspects',
        'category' => 'aspects',
        'title' => 'Fetch Category Aspects (schema cache)',
        'description' => 'Step 3 of Aspects: caches eBay\'s aspect SCHEMA (which Item Specifics a category supports, required vs. recommended, and — critically — the real allowed-values list, including compound entries like "Cartoon, TV & Movie Characters" that must never be comma-split) for every leaf category your listings use.',
        'usage_notes' => 'Run this whenever a listing lands in a category you haven\'t seen before, or periodically to pick up eBay schema changes. --refresh forces a re-fetch instead of using the cache.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/fetch_category_aspects.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 3,
        'output_files' => ['marketplaces/ebay/data/aspects/_index.csv'],
        'creates' => [
            [
                'file' => '_index.csv',
                'columns' => ['category_id', 'required_count', 'total_count'],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/listings.json',
                'label' => 'Listings roster — every listing\'s category gets its schema fetched. Produced by Export Listings.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => false,
                'options' => ['dows', 'ige'],
                'help' => 'Limit to one account\'s categories. Leave blank to cover both.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Cap how many categories to fetch.',
            ],
            [
                'name' => 'ids',
                'flag' => '--ids',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated category IDs to fetch instead of the full set.',
            ],
            [
                'name' => 'refresh',
                'flag' => '--refresh',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Re-fetch categories that already have a cached schema.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.audit-listings',
        'category' => 'aspects',
        'title' => 'Audit Listings (gap audit)',
        'description' => 'Step 4 of Aspects: diffs each listing\'s current Item Specifics against its category\'s aspect schema (from Fetch Category Aspects) and reports what\'s missing.',
        'usage_notes' => 'Requires Fetch Category Aspects to have run for this account\'s categories first, and Enrich Listings for the current aspects.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/audit_listings.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 4,
        'output_files' => [
            'marketplaces/ebay/data/{account}/output/aspect_gaps_summary.csv',
            'marketplaces/ebay/data/{account}/output/aspect_gaps_worklist.csv',
        ],
        'creates' => [
            [
                'file' => 'aspect_gaps_summary.csv',
                'columns' => [
                    'priority', 'item_id', 'title', 'category_id', 'category_path', 'schema_aspects',
                    'present', 'missing_required', 'missing_recommended', 'missing_required_names',
                    'missing_recommended_names',
                ],
            ],
            [
                'file' => 'aspect_gaps_worklist.csv',
                'columns' => [
                    'item_id', 'category_id', 'aspect', 'importance', 'mode', 'cardinality',
                    'allowed_values', 'values_sample', 'title',
                ],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/aspects/_index.csv',
                'label' => 'Category aspect schema cache — what "missing" is measured against. Produced by Fetch Category Aspects.',
            ],
            [
                'path' => 'marketplaces/ebay/data/{account}/output/items/',
                'label' => 'Per-listing current aspects — what\'s already present. Produced by Enrich Listings.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.fill-aspects',
        'category' => 'aspects',
        'title' => 'Fill Aspects (deterministic gap-fill)',
        'description' => 'Step 5 of Aspects: proposes values for the gaps Audit Listings found, from the Usurper inventory export plus constant defaults — constrained to each aspect\'s allowed-value list. Does not touch eBay.',
        'usage_notes' => 'Omit --export to auto-pick the newest InventoryExport_*.csv already in this account\'s input folder. Produces proposed_fills.csv, which Read Aspects (build worksheet) folds into review_sheet.csv as proposed_value.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/fill_aspects.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 5,
        'output_files' => ['marketplaces/ebay/data/{account}/output/proposed_fills.csv'],
        'creates' => [
            [
                'file' => 'proposed_fills.csv',
                'columns' => [
                    'item_id', 'sku', 'name', 'category_id', 'aspect', 'importance', 'mode',
                    'proposed_value', 'source', 'ai_generated', 'status', 'title',
                ],
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'export',
                'flag' => '--export',
                'type' => 'file',
                'required' => false,
                'help' => 'The Usurper inventory export CSV to fill from. Leave blank to auto-pick the newest one already on disk.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.author-aspects-ai',
        'category' => 'aspects',
        'title' => 'Author Aspects (AI)',
        'description' => 'Step 5 of Aspects (AI path, alongside Fill Aspects): calls the Anthropic API directly to propose values for every gap Fill Aspects\' deterministic pass couldn\'t reach, honestly self-rated with a certainty percentage. Writes proposed_fills_deep.csv, which Read Aspects folds in as another proposed_value source alongside Fill Aspects\' own proposals. Never touches eBay — writes local files only.',
        'usage_notes' => 'This calls a paid API — real cost per run, printed at the end. Always run --dry-run first to see the chunk plan and an example prompt at no cost. Requires Audit Listings and Fill Aspects to have already run for this account (reads aspect_gaps_worklist.csv and proposed_fills.csv). Every gap allowed to have a closed value list (SELECTION_ONLY) is grounded with that exact list so the AI can\'t propose something eBay would reject; free-text aspects get a plain factual value. Unlike Author Descriptions (AI), rerunning this reprocesses every remaining gap again from scratch — there\'s no already-answered skip, so avoid rerunning back-to-back without a reason (it costs money each time).',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/ai_review.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 5,
        'output_files' => [
            'marketplaces/ebay/data/{account}/output/ai_fill_answers.jsonl',
            'marketplaces/ebay/data/{account}/output/proposed_fills_deep.csv',
        ],
        'creates' => [
            [
                'file' => 'proposed_fills_deep.csv',
                'columns' => [
                    'item_id', 'sku', 'name', 'category_id', 'aspect', 'mode', 'proposed_value',
                    'source', 'ai_generated', 'certainty', 'status', 'title',
                ],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/aspect_gaps_worklist.csv',
                'label' => 'Aspect Gaps Worklist — every (listing x missing aspect) this considers filling. Produced by Audit Listings.',
            ],
            [
                'path' => 'marketplaces/ebay/data/{account}/output/proposed_fills.csv',
                'label' => 'Fill Aspects\' own proposals — gaps already filled here are skipped, not reprocessed by the AI.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'mode',
                'flag' => '--mode',
                'type' => 'enum',
                'required' => true,
                'default' => 'deep',
                'options' => ['deep'],
                'help' => 'ai_review.php also has blanks/current modes for a manual human-review loop — this page only exposes the fully-automated deep-fill path.',
            ],
            [
                'name' => 'run',
                'flag' => '--run',
                'type' => 'bool',
                'required' => true,
                'default' => true,
                'help' => 'Calls the Anthropic API directly. Required — this is the only action this page runs (the alternative is the manual --tasks/--merge loop from the command line).',
            ],
            [
                'name' => 'dry-run',
                'flag' => '--dry-run',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Show the chunk plan and an example prompt. No API calls, no cost, no writes.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Cap how many products (not gaps) to process.',
            ],
            [
                'name' => 'chunk-size',
                'flag' => '--chunk-size',
                'type' => 'int',
                'required' => false,
                'default' => 5,
                'help' => 'Products per API call. Default 5.',
            ],
            [
                'name' => 'model',
                'flag' => '--model',
                'type' => 'enum',
                'required' => false,
                'default' => 'claude-sonnet-4-6',
                'options' => ['claude-haiku-4-5', 'claude-sonnet-4-6', 'claude-opus-4-8'],
                'help' => 'Default claude-sonnet-4-6.',
            ],
            [
                'name' => 'max-allowed',
                'flag' => '--max-allowed',
                'type' => 'int',
                'required' => false,
                'default' => 80,
                'help' => 'A SELECTION_ONLY aspect with more than this many allowed values is treated as free text instead of grounding the AI with the full list. Default 80.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.apply-review-rules',
        'category' => 'aspects',
        'title' => 'Apply Review Rules (deterministic proposing)',
        'description' => 'Step 7 of Aspects: applies the inventory lead\'s general proposing rules to review_sheet.csv\'s proposed_value column — deterministic snap-to-standard-value logic, not an LLM judgment call. DRY-RUN: writes into review_sheet.csv locally, never touches eBay.',
        'usage_notes' => 'Run after Read Aspects (worksheet mode) has built review_sheet.csv. Every change this makes is also logged into reviewer_notes so it always traces back to this script.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/apply_review_rules.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 7,
        'optional' => true,
        'output_files' => ['marketplaces/ebay/data/{account}/output/review_sheet.csv'],
        'creates' => [
            [
                'file' => 'review_sheet.csv',
                'columns' => [
                    'item_id', 'sku', 'varied_by', 'name', 'category_id', 'aspect', 'mode',
                    'cardinality', 'source', 'certainty', 'current_value', 'proposed_value',
                    'approved_value', 'reviewer_notes', 'allowed_values', 'title',
                ],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/review_sheet.csv',
                'label' => 'Review Sheet — the proposed_value column this rewrites in place. Produced by Read Aspects.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'dry',
                'flag' => '--dry',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Preview what would change without writing review_sheet.csv.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.normalize-review-sheet-units',
        'category' => 'aspects',
        'title' => 'Normalize Units (review sheet)',
        'description' => 'Step 9 of Aspects: normalizes unit measurements in review_sheet.csv\'s proposed_value column (e.g. "0.0800" -> "0.08 lb") for accounts that haven\'t had a human review round-trip yet. Formatting only — never changes the underlying value, and appends to reviewer_notes rather than overwriting it.',
        'usage_notes' => 'Use this one when there\'s no separate returned handoff CSV to normalize (see Normalize Units (handoff CSV) for that case instead). Overwrites review_sheet.csv in place unless --out is given.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/normalize_review_sheet_units.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 9,
        'output_files' => ['marketplaces/ebay/data/{account}/output/review_sheet.csv'],
        'creates' => [
            [
                'file' => 'review_sheet.csv',
                'columns' => [
                    'item_id', 'sku', 'varied_by', 'name', 'category_id', 'aspect', 'mode',
                    'cardinality', 'source', 'certainty', 'current_value', 'proposed_value',
                    'approved_value', 'reviewer_notes', 'allowed_values', 'title',
                ],
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'dry-run',
                'flag' => '--dry-run',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Preview what would change without writing review_sheet.csv.',
            ],
            [
                'name' => 'out',
                'flag' => '--out',
                'type' => 'string',
                'required' => false,
                'help' => 'Write the normalized copy to a new path instead of overwriting review_sheet.csv in place. Leave blank to overwrite in place (a .preunitnorm.bak backup is made automatically).',
            ],
        ],
    ],
    [
        'slug' => 'ebay.normalize-handoff-units',
        'category' => 'aspects',
        'title' => 'Normalize Units (handoff CSV)',
        'description' => 'Step 9 of Aspects (alternate path): normalizes unit measurements in a reviewer-returned handoff CSV (item_id, sku, aspect, final_value shape) so the batch can go back out for a second review pass. Cross-references review_sheet.csv to find each item\'s vary-by aspect and never normalizes a variation-defining value.',
        'usage_notes' => 'Use this one when a human reviewer already returned a handoff CSV (see Normalize Units (review sheet) for the no-round-trip case instead). Writes a new file — give --out a path, or it defaults alongside the input.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/normalize_handoff_units.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 9,
        'output_files' => [],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/review_sheet.csv',
                'label' => 'Review Sheet — cross-referenced to find each item\'s vary-by aspect so it\'s never normalized.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account this handoff CSV belongs to.',
            ],
            [
                'name' => 'input',
                'flag' => '--input',
                'type' => 'file',
                'required' => true,
                'help' => 'The reviewer-returned handoff CSV to normalize.',
            ],
            [
                'name' => 'out',
                'flag' => '--out',
                'type' => 'string',
                'required' => false,
                'help' => 'Output path for the normalized copy. Leave blank for a default path alongside the input.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.write-canary-test',
        'category' => 'aspects',
        'title' => 'Write Canary Test (single-item test write)',
        'description' => 'Step 11 of Aspects: pushes a small, hand-picked set of item/sku/aspect/final_value rows to eBay via ReviseItem, one item at a time — a safety check on a handful of real listings before trusting Apply Aspects with the full account.',
        'usage_notes' => 'Reads canary_test_ids.csv (a short hand-picked list) from this account\'s output folder — not the full review_sheet.csv. Dry-run by default; --verify round-trips through eBay without committing; --live actually writes.',
        'type' => 'write',
        'cli_path' => 'marketplaces/ebay/scripts/write_canary_test.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 11,
        'optional' => true,
        'output_files' => [],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/canary_test_ids.csv',
                'label' => 'Canary Test IDs — the short hand-picked list of item/sku/aspect/final_value rows this pushes. You maintain this file yourself before running.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'item',
                'flag' => '--item',
                'type' => 'string',
                'required' => false,
                'help' => 'A single item ID from canary_test_ids.csv to run against. Leave blank to run every row in the file.',
            ],
            [
                'name' => 'list',
                'flag' => '--list',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Just list what canary_test_ids.csv contains, no write.',
            ],
            [
                'name' => 'verify',
                'flag' => '--verify',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Round-trip through eBay to validate the payload without committing.',
            ],
            [
                'name' => 'live',
                'flag' => '--live',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to eBay (requires retyping the item id to confirm).',
            ],
        ],
    ],
    [
        'slug' => 'ebay.check-connection',
        'category' => 'diagnostics',
        'title' => 'Check Connection',
        'description' => 'Proves this app can actually talk to eBay for an account end-to-end — mints an application token, confirms the API keys are valid, and reports what\'s working. The thing to run first when anything else in this app starts failing with an auth error.',
        'usage_notes' => 'No output file — this just prints a pass/fail report. --all checks every configured account in one run.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/check_connection.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'output_files' => [],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => false,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to check. Leave blank with --all to check every account.',
            ],
            [
                'name' => 'mode',
                'flag' => '--mode',
                'type' => 'enum',
                'required' => false,
                'options' => ['production', 'sandbox'],
                'help' => 'Which eBay environment to check against. Defaults to production.',
            ],
            [
                'name' => 'all',
                'flag' => '--all',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Check every configured account instead of just one.',
            ],
        ],
        'connection_check' => true,
    ],
    [
        'slug' => 'ebay.backup-current-state',
        'category' => 'diagnostics',
        'title' => 'Backup Current State',
        'description' => 'Snapshots an account\'s current live eBay data (aspects and/or description HTML) into a timestamped backup folder, so there\'s always something to revert to. Run this before a live write if /backups shows no recent backup for the account you\'re about to touch.',
        'usage_notes' => 'Read-only against eBay — makes no changes. Saves to marketplaces/ebay/data/{account}/backups/dowscripts_{what}_{timestamp}/, visible on the Backups page afterward.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/backup_current_state.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'output_files' => [],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to back up.',
            ],
            [
                'name' => 'what',
                'flag' => '--what',
                'type' => 'enum',
                'required' => false,
                'default' => 'all',
                'options' => ['aspects', 'descriptions', 'all'],
                'help' => 'What to snapshot. Defaults to both aspects and descriptions.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Only back up the first N listings — useful for a quick smoke test before a full run.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.build-current-live-attributes',
        'category' => 'aspects',
        'title' => 'Current Live Aspects (snapshot)',
        'description' => 'A fresh, read-only pull of every listing\'s CURRENT live Item Specifics, right now — a "what does eBay actually show today" sheet independent of review_sheet.csv\'s proposal/approval workflow. Includes blank schema-defined gap rows, not just filled ones, so it keeps the real-vs-custom-attribute signal intact.',
        'usage_notes' => 'Not a required pipeline step — run any time you want a clean current-state export to hand someone (e.g. for a spot audit) without touching the in-progress review workflow. Reads Export Listings\' roster; produces an empty report if that hasn\'t run yet for this account.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/build_current_live_attributes.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'output_files' => ['marketplaces/ebay/data/{account}/output/current_live_attributes_v3_{account}.csv'],
        'creates' => [
            [
                'file' => 'current_live_attributes_v3_{account}.csv',
                'columns' => [
                    'item_id', 'sku', 'varied_by', 'name', 'category_id', 'aspect', 'mode',
                    'cardinality', 'current_value', 'allowed_values', 'title',
                ],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/listings.json',
                'label' => 'Listings roster — every listing this walks. Produced by Export Listings.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Cap how many listings to include.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.mark-prop65-delete',
        'category' => 'aspects',
        'title' => 'Mark Prop65 for Deletion',
        'description' => 'Owner-directed one-time cleanup (2026-07): the Prop65 warning now lives in the description as a badge image instead of an item aspect. This marks approved_value = DELETE on every review_sheet.csv row where the Prop65 aspect is still live — an audit-trail marker only, no eBay write here.',
        'usage_notes' => 'Must run AFTER the last Read Aspects call for the account (which always resets approved_value) and BEFORE Delete Prop65 (live write). This is a one-time policy migration, not a step you run every cycle.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/mark_prop65_delete.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'output_files' => ['marketplaces/ebay/data/{account}/output/review_sheet.csv'],
        'creates' => [
            [
                'file' => 'review_sheet.csv',
                'columns' => [
                    'item_id', 'sku', 'varied_by', 'name', 'category_id', 'aspect', 'mode',
                    'cardinality', 'source', 'certainty', 'current_value', 'proposed_value',
                    'approved_value', 'reviewer_notes', 'allowed_values', 'title',
                ],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/review_sheet.csv',
                'label' => 'Review Sheet — the approved_value column this marks DELETE on Prop65 rows. Produced by Read Aspects.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'dry',
                'flag' => '--dry',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Preview what would be marked without writing review_sheet.csv.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.delete-prop65-live',
        'category' => 'aspects',
        'title' => 'Delete Prop65 (live write)',
        'description' => 'The live eBay write that actually removes the Prop65 warning from item specifics. Deliberately does NOT source from approved_value/apply_set.json — builds each item\'s outgoing ItemSpecifics from its own cached current state with only the Prop65 key removed, so unrelated pending approvals never get bundled into this write.',
        'usage_notes' => 'One-time policy migration (2026-07), not a step you run every cycle — see Mark Prop65 for Deletion first. Use item, items, or offset+limit to narrow the run — leave all three blank to target every eligible item in the account (still gated by --confirm=WRITE for a bulk live run). Dry-run by default; --verify round-trips through eBay without committing; --live actually writes.',
        'type' => 'write',
        'cli_path' => 'marketplaces/ebay/scripts/delete_prop65_live.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'output_files' => ['marketplaces/ebay/data/{account}/output/delete_prop65_run.csv'],
        'creates' => [
            [
                'file' => 'delete_prop65_run.csv',
                'columns' => ['timestamp', 'item_id', 'verify_only', 'ack', 'errors', 'removed_value'],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/items/',
                'label' => 'Per-listing current-state snapshots — this script builds its outgoing ItemSpecifics from these, with only the Prop65 key removed. Produced by Enrich Listings.',
            ],
            [
                'path' => 'marketplaces/ebay/data/{account}/output/review_sheet.csv',
                'label' => 'Review Sheet — source for the unchanged variation-child values sent alongside a variation listing\'s parent specifics. Produced by Read Aspects.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'item',
                'flag' => '--item',
                'type' => 'string',
                'required' => false,
                'help' => 'A single item ID to run against.',
            ],
            [
                'name' => 'items',
                'flag' => '--items',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated item IDs to run against.',
            ],
            [
                'name' => 'offset',
                'flag' => '--offset',
                'type' => 'int',
                'required' => false,
                'help' => 'Skip this many items before starting (paired with limit).',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Process at most this many items (paired with offset).',
            ],
            [
                'name' => 'exclude',
                'flag' => '--exclude',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated item IDs to skip.',
            ],
            [
                'name' => 'verify',
                'flag' => '--verify',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Round-trip through eBay to validate the payload without committing.',
            ],
            [
                'name' => 'live',
                'flag' => '--live',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to eBay.',
            ],
            [
                'name' => 'confirm',
                'flag' => '--confirm',
                'type' => 'string',
                'required' => false,
                'help' => 'Must be exactly WRITE for a bulk (more than one item) live run.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.build-image-review',
        'category' => 'images',
        'title' => 'Build Image Review',
        'description' => 'Turns Audit Media\'s media_summary.csv + media_images.csv into a per-listing image remediation worklist — broken/missing/low-resolution images and a recommended action, with blank approved/reviewer_notes columns for a reviewer to fill in. No eBay writes. Always processes BOTH dows and ige in one run — there\'s no account selector, unlike most other scripts here.',
        'usage_notes' => 'Requires Audit Media to have run for an account first, or that account is silently skipped.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/build_image_review.py',
        'interpreter' => 'python3',
        'featured' => true,
        'step' => 1,
        'output_files' => [
            'marketplaces/ebay/data/dows/output/image_review.csv',
            'marketplaces/ebay/data/ige/output/image_review.csv',
        ],
        'creates' => [
            [
                'file' => 'image_review.csv',
                'columns' => [
                    'item_id', 'sku', 'title', 'image_count', 'all_eps', 'non_eps_images',
                    'min_long_px', 'below_zoom_800', 'below_ideal', 'priority', 'issue',
                    'recommended_action', 'self_hosted_urls', 'low_res_urls', 'approved', 'reviewer_notes',
                ],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/dows/output/media_summary.csv',
                'label' => 'Media Summary (dows) — the per-listing image facts this scores. Produced by Audit Media.',
            ],
            [
                'path' => 'marketplaces/ebay/data/ige/output/media_summary.csv',
                'label' => 'Media Summary (ige) — the per-listing image facts this scores. Produced by Audit Media.',
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'ebay.fetch-all-category-upc-support',
        'category' => 'upc-gtin',
        'title' => 'Fetch All Category UPC Support',
        'description' => 'Step 1 of UPC/GTIN: lists every eBay US leaf category ID with a true/false column for whether UPC is actually required (the red-star must-fill field) — not just the categories your own listings happen to use.',
        'usage_notes' => 'Shared across both accounts — no --account flag. Run this once, or with --refresh when you suspect eBay changed category requirements.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/fetch_all_category_upc_support.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 1,
        'output_files' => ['marketplaces/ebay/data/aspects/all_categories_upc_support.csv'],
        'creates' => [
            [
                'file' => 'all_categories_upc_support.csv',
                'columns' => ['category_id', 'category_name', 'upc_essential'],
            ],
        ],
        'params' => [
            [
                'name' => 'refresh',
                'flag' => '--refresh',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Re-fetch categories that already have a cached result.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Cap how many categories to check.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.build-gtin-report',
        'category' => 'upc-gtin',
        'title' => 'Build GTIN Report',
        'description' => 'Step 2 of UPC/GTIN: a per-listing report of the real product identifier (ProductListingDetails.UPC/EAN/ISBN, whichever the seller supplied) — spots listings missing a UPC entirely.',
        'usage_notes' => 'A different field than item aspects — this is ProductListingDetails, not ItemSpecifics.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/build_gtin_report.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 2,
        'output_files' => ['marketplaces/ebay/data/{account}/output/gtin_report_{account}.csv'],
        'creates' => [
            [
                'file' => 'gtin_report_{account}.csv',
                'columns' => [
                    'item_id', 'sku', 'varied_by', 'title', 'upc', 'ean', 'isbn', 'gtin',
                    'missing_gtin', 'custom_upc_specific', 'upc_duplicated',
                ],
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Cap how many listings to include.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.check-upc-category-support',
        'category' => 'upc-gtin',
        'title' => 'Check UPC Category Support',
        'description' => 'Step 3 of UPC/GTIN: per category actually used by this account\'s listings, does eBay support/require the real identifier field at all — the missing piece needed to know whether a blank UPC is actually a problem for that listing.',
        'usage_notes' => 'Run after Build Apply Set (for the authoritative per-listing category) and Enrich Listings (for category_coverage.csv) — reads both, not Build GTIN Report\'s output.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/check_upc_category_support.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 3,
        'output_files' => ['marketplaces/ebay/data/{account}/output/upc_category_support_{account}.csv'],
        'creates' => [
            [
                'file' => 'upc_category_support_{account}.csv',
                'columns' => ['category_id', 'category_path', 'listing_count', 'upc_support', 'ean_support', 'isbn_support'],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/apply_set.json',
                'label' => 'Apply Set — the authoritative per-listing category assignment. Produced by Build Apply Set.',
            ],
            [
                'path' => 'marketplaces/ebay/data/{account}/output/category_coverage.csv',
                'label' => 'Category Coverage — listing counts per category. Produced by Enrich Listings.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.build-upc-worksheet',
        'category' => 'upc-gtin',
        'title' => 'Build UPC Worksheet',
        'description' => 'Step 4 of UPC/GTIN: joins Build GTIN Report\'s per-listing data with Check UPC Category Support\'s per-category data into the worksheet a reviewer fills in with real UPC values. No fresh API calls — pure join of already-collected data.',
        'usage_notes' => 'Requires Build GTIN Report and Check UPC Category Support to have already run for this account. Writes eBay_DOWS_upc-worksheet_REVIEW.csv or eBay_IGE_upc-worksheet_REVIEW.csv (account name uppercase in the filename) — not shown as a downloadable output on this run\'s page because of that, but it lands in the account\'s own output folder same as everything else.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/build_upc_worksheet.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 4,
        'output_files' => [],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/gtin_report_{account}.csv',
                'label' => 'GTIN Report — produced by Build GTIN Report.',
            ],
            [
                'path' => 'marketplaces/ebay/data/{account}/output/upc_category_support_{account}.csv',
                'label' => 'UPC Category Support — produced by Check UPC Category Support.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.write-gtin',
        'category' => 'upc-gtin',
        'title' => 'Write GTIN (live write)',
        'description' => 'Step 5 of UPC/GTIN: writes a real product identifier (UPC/EAN) to a single listing\'s ProductListingDetails via ReviseItem. A different field than Apply Aspects writes (ItemSpecifics) — only Item->ItemID and ProductListingDetails->UPC go in the request, nothing else on the listing is touched.',
        'usage_notes' => 'One listing at a time — no bulk mode. Dry-run by default; --verify round-trips through eBay without committing; --live actually writes.',
        'type' => 'write',
        'cli_path' => 'marketplaces/ebay/scripts/write_gtin.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 5,
        'output_files' => [],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'item',
                'flag' => '--item',
                'type' => 'string',
                'required' => true,
                'help' => 'The item ID to write the UPC to.',
            ],
            [
                'name' => 'upc',
                'flag' => '--upc',
                'type' => 'string',
                'required' => true,
                'help' => 'The real UPC/EAN value to write.',
            ],
            [
                'name' => 'verify',
                'flag' => '--verify',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Round-trip through eBay to validate the payload without committing.',
            ],
            [
                'name' => 'live',
                'flag' => '--live',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to eBay.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.spot-check-upc-country',
        'category' => 'upc-gtin',
        'title' => 'Spot-Check UPC/Country Removal',
        'description' => 'Step 6 of UPC/GTIN: read-only live audit confirming the custom "UPC" and "Country/Region of Manufacture" ItemSpecifics are actually gone from a sample of item IDs, straight from eBay\'s live GetItem response.',
        'usage_notes' => 'Give it a plain text file, one item ID per line. Its own output filename is fixed to the date it was first written (2026-07-09) regardless of when you rerun it — the columns still reflect today\'s live data, only the filename is frozen.',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/spot_check_upc_country.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 6,
        'output_files' => ['marketplaces/ebay/data/{account}/output/upc_country_region_spot_check_2026-07-09.csv'],
        'creates' => [
            [
                'file' => 'upc_country_region_spot_check_2026-07-09.csv',
                'columns' => ['item_id', 'upc_present', 'country_region_present', 'status', 'note'],
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'file',
                'flag' => '--file',
                'type' => 'file',
                'required' => true,
                'help' => 'Plain text file of item IDs to spot-check, one per line.',
            ],
        ],
    ],

    // --- Two-pack listing creation (SCAFFOLD — see each script's own docblock) --
    // Turn cheap single listings (under $20) into new "2-pack" listings. Business
    // rules live in marketplaces/ebay/docs/two_pack_rules.txt. Find 2-Pack
    // Candidates' output IS the human review step: every row gets an `approved`
    // column (defaults to yes), and Create 2-Pack Listings refuses to touch any
    // row explicitly marked `no`, even via --item/--items.
    [
        'slug' => 'ebay.find-two-pack-candidates',
        'category' => 'two-pack',
        'title' => 'Find 2-Pack Candidates',
        'description' => 'Scans the account\'s listings under $20 (from Export Listings) and pulls real data via GetItem to build a reviewable shortlist — every row includes a computed new_title/new_price/new_quantity preview and an approved column (defaults to yes) for whoever reviews the file.',
        'usage_notes' => 'Read-only — no writes to eBay. Run Export Listings first so skus.csv exists. The output file is meant to be sent for review before Create 2-Pack Listings runs — flip a row\'s approved column to "no" to exclude it. The issues column explains anything worth a second look: a title that got truncated (couldn\'t fit 80 chars, with an AI-assisted shorten attempted first if ANTHROPIC_API_KEY is set), or a source title that already mentions a pack/multi-unit (quantity math may need a manual check).',
        'type' => 'read',
        'cli_path' => 'marketplaces/ebay/scripts/find_two_pack_candidates.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 1,
        'output_files' => [
            'marketplaces/ebay/data/{account}/output/two_pack_candidates.csv',
        ],
        'creates' => [
            [
                'file' => 'two_pack_candidates.csv',
                'columns' => [
                    'item_id', 'sku', 'title', 'price', 'weight_lbs', 'quantity', 'category_id', 'category_name',
                    'is_variation', 'new_title', 'new_price', 'new_quantity', 'approved', 'issues',
                ],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/skus.csv',
                'label' => 'SKUs — the roster this reads from (produced by Export Listings).',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'max-price',
                'flag' => '--max-price',
                'type' => 'string',
                'required' => false,
                'default' => '20.00',
                'help' => 'Max current price to consider ($20 default; weight does not factor in).',
            ],
            [
                'name' => 'max-weight-lbs',
                'flag' => '--max-weight-lbs',
                'type' => 'string',
                'required' => false,
                'help' => 'Optional weight cutoff in lbs — unset by default, since weight is no longer a selection criterion.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Cap how many priced-under-threshold listings get a GetItem check.',
            ],
            [
                'name' => 'no-ai-shrink',
                'flag' => '--no-ai-shrink',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Skip the AI-assisted title shorten even if ANTHROPIC_API_KEY is set — overflowing titles are truncated + flagged instead.',
            ],
        ],
    ],
    [
        'slug' => 'ebay.create-two-pack-listings',
        'category' => 'two-pack',
        'title' => 'Create 2-Pack Listings (live write)',
        'description' => 'Creates a new fixed-price "2-pack" listing for each APPROVED candidate, built from that candidate\'s existing listing via GetItem. Never revises the source listing.',
        'usage_notes' => 'Only processes rows the candidates file marks approved=yes (the default) — a row marked "no" is skipped entirely, even under --item/--items. Supports variation source items (keeps the full variation structure, e.g. all colors). Two rules are still genuinely open — title-overflow truncation past 80 chars, and the wording of the new "2 pack" item specific — see marketplaces/ebay/docs/two_pack_rules.txt. --verify is a genuinely separate, read-only eBay call (verifyAddFixedPriceItem) that creates nothing, safe to run freely. Dry-run by default; --live actually creates a new listing.',
        'type' => 'write',
        'cli_path' => 'marketplaces/ebay/scripts/create_two_pack_listings.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 2,
        'output_files' => [
            'marketplaces/ebay/data/{account}/output/create_two_pack_listings_run.csv',
        ],
        'creates' => [
            [
                'file' => 'create_two_pack_listings_run.csv',
                'columns' => ['timestamp', 'source_item_id', 'verify_only', 'new_sku', 'new_start_price', 'ack', 'new_item_id', 'errors'],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/ebay/data/{account}/output/two_pack_candidates.csv',
                'label' => 'Candidates — source list this reads from (produced by Find 2-Pack Candidates). Only rows with approved=yes (the default) are processed.',
            ],
        ],
        'params' => [
            [
                'name' => 'account',
                'flag' => '--account',
                'type' => 'enum',
                'required' => true,
                'options' => ['dows', 'ige'],
                'help' => 'Which eBay seller account to run against.',
            ],
            [
                'name' => 'item',
                'flag' => '--item',
                'type' => 'string',
                'required' => false,
                'help' => 'A single source item ID to run against.',
            ],
            [
                'name' => 'items',
                'flag' => '--items',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated source item IDs to run against.',
            ],
            [
                'name' => 'offset',
                'flag' => '--offset',
                'type' => 'int',
                'required' => false,
                'help' => 'Skip this many candidates before starting (paired with limit).',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Process at most this many candidates (paired with offset).',
            ],
            [
                'name' => 'exclude',
                'flag' => '--exclude',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated source item IDs to skip.',
            ],
            [
                'name' => 'verify',
                'flag' => '--verify',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Round-trip through eBay to validate the new listing without creating it.',
            ],
            [
                'name' => 'live',
                'flag' => '--live',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually create the new listing live on eBay.',
            ],
            [
                'name' => 'confirm',
                'flag' => '--confirm',
                'type' => 'string',
                'required' => false,
                'help' => 'Must be exactly WRITE for a --live run over more than one candidate.',
            ],
        ],
    ],
];
