<?php

declare(strict_types=1);

// Each entry here is untrusted input from ScriptRegistry's point of view — see
// App\Scripts\ScriptDefinition::fromArray() for the validation boundary. Field
// shapes are transcribed from each script's own docblock/usage line and its real
// $argv parsing, not guessed — see shopify/README.md's own pipeline table, which
// already documents this exact step order.
//
// Unlike eBay (two seller accounts, dows/ige), Shopify is a single store
// (asroutdoor.myshopify.com) — no script here takes an --account flag, and none
// of these scripts are registered in config/credentials.php: they read
// SHOP_DOMAIN/ADMIN_API_TOKEN straight from .env via lib/bootstrap.php, the same
// as every eBay script reads its own credentials, just without DOWScripts'
// per-account env injection layer since there's only ever one account.

return [
    [
        'slug' => 'shopify.audit-products',
        'category' => 'core',
        'title' => 'Audit Products',
        'description' => 'Step 0 of the core pipeline: gap audit of every product\'s SEO description, product type, and image alt text, with a priority flag per gap.',
        'usage_notes' => 'Read-only. Run this first — everything else in the core pipeline works from products it flags. No flags, always runs against the full catalog.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/audit_products.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 1,
        'output_files' => ['marketplaces/shopify/data/output/products_audit.csv'],
        'creates' => [
            [
                'file' => 'products_audit.csv',
                'columns' => [
                    'numeric_id', 'gid', 'handle', 'title', 'status', 'vendor', 'product_type',
                    'category', 'seo_title', 'seo_desc', 'seo_desc_len', 'body_len', 'tags_count',
                    'image_alt', 'url', 'missing_seo_description', 'seo_too_short', 'seo_too_long',
                    'missing_category', 'missing_product_type', 'thin_body', 'missing_vendor',
                    'missing_image', 'missing_image_alt', 'priority',
                ],
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'shopify.audit-feed',
        'category' => 'core',
        'title' => 'Audit Feed',
        'description' => 'GTIN/image/availability gap audit — the shopping-feed-specific checks Audit Products doesn\'t cover.',
        'usage_notes' => 'Read-only. No flags, always runs against the full catalog.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/audit_feed.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 1,
        'output_files' => ['marketplaces/shopify/data/output/feed_audit.csv'],
        'creates' => [
            [
                'file' => 'feed_audit.csv',
                'columns' => [
                    'numeric_id', 'title', 'status', 'vendor', 'variants', 'no_barcode', 'no_sku',
                    'images', 'min_img_edge', 'no_barcode_any', 'no_barcode_some', 'no_sku_any',
                    'no_category', 'no_brand', 'not_active', 'not_available', 'no_image',
                    'image_below_500', 'no_storefront_url',
                ],
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'shopify.export-descriptions',
        'category' => 'core',
        'title' => 'Export Descriptions (grounding pack)',
        'description' => 'Step 1 of the core pipeline: pulls every product\'s current title/description/type as the grounding material an authoring pass may only add to, never invent beyond.',
        'usage_notes' => 'Read-only. Feeds Assemble Output once you\'ve authored replacements in data/drafts/drafts_manual.json.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/export_descriptions.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 2,
        'output_files' => [
            'marketplaces/shopify/data/input/phase2_input.json',
            'marketplaces/shopify/data/output/phase2_preview.csv',
        ],
        'creates' => [
            [
                'file' => 'phase2_preview.csv',
                'columns' => ['numeric_id', 'title', 'product_type', 'category', 'body_len', 'weak_source', 'body_snippet'],
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'shopify.export-image-alts',
        'category' => 'core',
        'title' => 'Export Image Alts (grounding pack)',
        'description' => 'Step 1 of the core pipeline: pulls every product\'s current featured-image alt text and media ID as the grounding material for an alt-text authoring pass.',
        'usage_notes' => 'Read-only. Feeds Assemble Output once you\'ve authored replacements in data/drafts/drafts_alt.json.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/export_image_alts.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 2,
        'output_files' => ['marketplaces/shopify/data/input/image_alts.json'],
        'params' => [],
    ],
    [
        'slug' => 'shopify.export-variants',
        'category' => 'core',
        'title' => 'Export Variants (grounding pack)',
        'description' => 'Step 1 of the core pipeline: pulls every product\'s variant options/values, grounding material for anything that needs to know a product\'s real variant shape.',
        'usage_notes' => 'Read-only.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/export_variants.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 2,
        'output_files' => ['marketplaces/shopify/data/input/variants.json'],
        'params' => [],
    ],
    [
        'slug' => 'shopify.author-descriptions-ai',
        'category' => 'core',
        'title' => 'Author Descriptions (AI)',
        'description' => 'Step 2 of the core pipeline (AI path, alongside the export scripts): calls the Anthropic API directly to draft the SEO meta description and image alt text Assemble Output/Apply Metadata read — the automated alternative to authoring data/drafts/drafts_manual.json and drafts_alt.json by hand. The meta-description prompt is the already-reviewed drafting rules from marketplaces/shopify/rules/product-metadata-rules.md, loaded verbatim, not reinvented.',
        'usage_notes' => 'This calls a paid API — real cost per run, printed at the end. Always run --dry-run first to see the chunk plan and an example prompt at no cost. Requires Export Descriptions to have already run; also drafts alt text for any product present in image_alts.json (Export Image Alts), skipped otherwise. Skips products already in drafts_manual.json unless --ids is given.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/author_descriptions_ai.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 2,
        'output_files' => ['marketplaces/shopify/data/output/author_descriptions_ai_errors.csv'],
        'creates' => [
            [
                'file' => 'author_descriptions_ai_errors.csv',
                'columns' => ['numeric_id', 'reason', 'raw'],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/shopify/data/input/phase2_input.json',
                'label' => 'Grounding pack — the per-product source content this authors from. Produced by Export Descriptions.',
            ],
            [
                'path' => 'marketplaces/shopify/data/input/image_alts.json',
                'label' => 'Current image alt text — products present here also get alt text drafted. Produced by Export Image Alts.',
            ],
            [
                'path' => 'marketplaces/shopify/data/drafts/drafts_manual.json',
                'label' => 'Already-drafted meta descriptions — numeric_ids already in here are skipped by default (resumability). Use --ids to reprocess a specific one anyway.',
            ],
            [
                'path' => 'marketplaces/shopify/rules/product-metadata-rules.md',
                'label' => 'The exact prompt spec this sends to the API — the actual drafting rules the AI is asked to follow.',
            ],
        ],
        'params' => [
            [
                'name' => 'ids',
                'flag' => '--ids',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated numeric product IDs to (re-)draft regardless of whether already in drafts_manual.json. Leave blank to process undrafted products only.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Cap how many products to process.',
            ],
            [
                'name' => 'chunk-size',
                'flag' => '--chunk-size',
                'type' => 'int',
                'required' => false,
                'default' => 5,
                'help' => 'Products per API call. Default 5.',
            ],
            [
                'name' => 'model',
                'flag' => '--model',
                'type' => 'enum',
                'required' => false,
                'default' => 'claude-sonnet-4-6',
                'options' => ['claude-haiku-4-5', 'claude-sonnet-4-6', 'claude-opus-4-8'],
                'help' => 'Default claude-sonnet-4-6.',
            ],
            [
                'name' => 'dry-run',
                'flag' => '--dry-run',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Show the chunk plan and one example prompt. No API calls, no cost, no writes.',
            ],
        ],
    ],
    [
        'slug' => 'shopify.assemble-output',
        'category' => 'core',
        'title' => 'Assemble Output (build review sheet)',
        'description' => 'Step 2 of the core pipeline: merges the grounding packs with your authored drafts (data/drafts/drafts_manual.json, drafts_alt.json) into the reviewable before/after sheet Apply Metadata will read from. Offline — no Shopify calls.',
        'usage_notes' => 'Edit drafts_manual.json / drafts_alt.json, then rerun this to regenerate the reviewable output. Fills product_type for any blanks and ASCII-folds the whole output.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/assemble_output.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 3,
        'output_files' => [
            'marketplaces/shopify/data/output/phase2_output.json',
            'marketplaces/shopify/data/output/phase2_output.csv',
        ],
        'creates' => [
            [
                'file' => 'phase2_output.csv',
                'columns' => [
                    'numeric_id', 'title', 'old_product_type', 'new_product_type',
                    'old_seo_description', 'new_seo_description', 'new_desc_chars', 'old_image_alt',
                    'new_image_alt', 'image_alt_changed', 'weak_source', 'status',
                ],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/shopify/data/input/phase2_input.json',
                'label' => 'Descriptions grounding pack — produced by Export Descriptions.',
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'shopify.apply-metadata',
        'category' => 'core',
        'title' => 'Apply Metadata (live write)',
        'description' => 'Step 3 of the core pipeline: writes seo.description, productType, and image alt from Assemble Output\'s reviewed sheet live to Shopify.',
        'usage_notes' => 'Dry-run by default — logs intended changes, sends nothing. --apply actually writes (needs a token with write_products scope — the audit token is read-only and will 403 until re-authorized with Mint OAuth Token). Idempotent: reads current values first and skips rows already correct. --ids takes precedence over --limit.',
        'type' => 'write',
        'cli_path' => 'marketplaces/shopify/scripts/apply_metadata.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 4,
        'output_files' => [],
        'reference_files' => [
            [
                'path' => 'marketplaces/shopify/data/output/phase2_output.json',
                'label' => 'Review Sheet — the exact payload this pushes. Produced by Assemble Output.',
            ],
        ],
        'params' => [
            [
                'name' => 'apply',
                'flag' => '--apply',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to Shopify. Omit for a dry-run.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Process only the first N products — good for a small live canary.',
            ],
            [
                'name' => 'ids',
                'flag' => '--ids',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated product IDs to process instead — takes precedence over limit.',
            ],
        ],
    ],
    [
        'slug' => 'shopify.verify-applied',
        'category' => 'core',
        'title' => 'Verify Applied',
        'description' => 'Step 4 of the core pipeline: re-pulls the live catalog and diffs it against what Apply Metadata intended to write — catches silent partial failures the Admin API didn\'t error on.',
        'usage_notes' => 'Run this right after any Apply Metadata run. --csv also writes a per-product report; without it, this only prints to the run\'s output.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/verify_applied.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 5,
        'output_files' => ['marketplaces/shopify/data/output/phase3_verification.csv'],
        'creates' => [
            [
                'file' => 'phase3_verification.csv',
                'columns' => ['numeric_id', 'seo_description', 'product_type', 'image_alt'],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/shopify/data/output/phase2_output.json',
                'label' => 'What Apply Metadata intended to write — the baseline this diffs the live catalog against.',
            ],
        ],
        'params' => [
            [
                'name' => 'csv',
                'flag' => '--csv',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Also write a per-product CSV report, not just the console diff.',
            ],
        ],
    ],
    [
        'slug' => 'shopify.validate-storefront',
        'category' => 'core',
        'title' => 'Validate Storefront',
        'description' => 'Step 4 of the core pipeline (deeper check): fetches the live, rendered public product page (not just the Admin API\'s view) and confirms meta tags, OpenGraph, JSON-LD, and alt text actually reflect the change.',
        'usage_notes' => '--all checks every product (slower); --ids limits to specific ones. Read-only, hits the public storefront over HTTP.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/validate_storefront.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 5,
        'output_files' => [],
        'params' => [
            [
                'name' => 'all',
                'flag' => '--all',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Check every product instead of a sample. Slower.',
            ],
            [
                'name' => 'ids',
                'flag' => '--ids',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated product IDs to check.',
            ],
        ],
    ],
    [
        'slug' => 'shopify.audit-collections',
        'category' => 'collections',
        'title' => 'Audit Collections',
        'description' => 'Step 1 of Collections: gap audit for collection SEO metadata (title/description) — the collections equivalent of Audit Products.',
        'usage_notes' => 'Read-only. No flags.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/audit_collections.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 1,
        'output_files' => ['marketplaces/shopify/data/output/collections_audit.csv'],
        'creates' => [
            [
                'file' => 'collections_audit.csv',
                'columns' => [
                    'numeric_id', 'gid', 'handle', 'title', 'type', 'products_count', 'seo_title',
                    'seo_desc', 'seo_desc_len', 'body_len', 'image_alt', 'url',
                    'missing_seo_description', 'seo_too_short', 'seo_too_long', 'missing_body',
                    'thin_body', 'empty_collection', 'missing_image_alt', 'priority',
                ],
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'shopify.export-collection-products',
        'category' => 'collections',
        'title' => 'Export Collection Products (grounding pack)',
        'description' => 'Step 2 of Collections: pulls each collection\'s current body and member products as the grounding material for a metadata authoring pass.',
        'usage_notes' => 'Read-only.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/export_collection_products.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 2,
        'output_files' => ['marketplaces/shopify/data/output/collection_products.json'],
        'params' => [],
    ],
    [
        'slug' => 'shopify.apply-collection-metadata',
        'category' => 'collections',
        'title' => 'Apply Collection Metadata (live write)',
        'description' => 'Step 3 of Collections: writes seo.title/seo.description for collections from a reviewed data/output/collections_phase2.json — the collections equivalent of Apply Metadata.',
        'usage_notes' => 'Dry-run by default — --apply actually writes (needs write_products scope).',
        'type' => 'write',
        'cli_path' => 'marketplaces/shopify/scripts/apply_collection_metadata.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 3,
        'output_files' => [],
        'params' => [
            [
                'name' => 'apply',
                'flag' => '--apply',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to Shopify. Omit for a dry-run.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Process only the first N collections.',
            ],
        ],
    ],
    [
        'slug' => 'shopify.gtin-worklist',
        'category' => 'gtin-mpn',
        'title' => 'GTIN Worklist',
        'description' => 'Step 1 of GTIN/MPN: lists every variant\'s barcode status and builds the missing-GTIN worklist. Written at the variant level, which is what the feed actually reads from.',
        'usage_notes' => 'Read-only. No flags.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/gtin_worklist.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 1,
        'output_files' => [
            'marketplaces/shopify/data/output/gtin_status_all.csv',
            'marketplaces/shopify/data/output/gtin_missing.csv',
        ],
        'creates' => [
            [
                'file' => 'gtin_status_all.csv',
                'columns' => [
                    'product_id', 'handle', 'product_title', 'status', 'variant_id', 'variant_title',
                    'sku', 'current_barcode', 'gtin_state',
                ],
            ],
            [
                'file' => 'gtin_missing.csv',
                'columns' => [
                    'product_id', 'handle', 'product_title', 'product_type', 'variant_id',
                    'variant_title', 'sku', 'gtin_to_fill',
                ],
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'shopify.apply-mpn-gtin',
        'category' => 'gtin-mpn',
        'title' => 'Apply MPN/GTIN (live write)',
        'description' => 'Step 2 of GTIN/MPN: authoritative GTIN-14 + MPN back-fill from the reviewed worklist. Idempotent — reads current barcode + mpn per variant first and writes only the deltas; a failing GTIN check digit is skipped and reported, never written.',
        'usage_notes' => 'Dry-run by default — --apply actually writes (needs write_products scope). --only limits to one side.',
        'type' => 'write',
        'cli_path' => 'marketplaces/shopify/scripts/apply_mpn_gtin.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 2,
        'output_files' => [],
        'reference_files' => [
            [
                'path' => 'marketplaces/shopify/data/output/mpn_worklist_updated.csv',
                'label' => 'The reviewed worklist this reads from.',
            ],
        ],
        'params' => [
            [
                'name' => 'apply',
                'flag' => '--apply',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to Shopify. Omit for a dry-run.',
            ],
            [
                'name' => 'only',
                'flag' => '--only',
                'type' => 'enum',
                'required' => false,
                'options' => ['gtin', 'mpn', 'both'],
                'help' => 'Do just one side instead of both.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Process only the first N worklist rows.',
            ],
            [
                'name' => 'ids',
                'flag' => '--ids',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated variant IDs to process instead.',
            ],
        ],
    ],
    [
        'slug' => 'shopify.apply-product-mpn',
        'category' => 'gtin-mpn',
        'title' => 'Apply Product MPN (live write)',
        'description' => 'Step 3 of GTIN/MPN: mirrors variant MPN up to the product-level mpn metafield, for single-variant products only.',
        'usage_notes' => 'Dry-run by default — --apply actually writes.',
        'type' => 'write',
        'cli_path' => 'marketplaces/shopify/scripts/apply_product_mpn.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 3,
        'output_files' => [],
        'params' => [
            [
                'name' => 'apply',
                'flag' => '--apply',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to Shopify. Omit for a dry-run.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Process only the first N products.',
            ],
        ],
    ],
    [
        'slug' => 'shopify.apply-variant-google-shopping',
        'category' => 'gtin-mpn',
        'title' => 'Apply Variant Google Shopping (live write)',
        'description' => 'Writes variant-level condition/gender/age_group/size_system/size_type metafields.',
        'usage_notes' => 'Standalone — not part of the GTIN/MPN sequence, run any time. Dry-run by default — --apply actually writes.',
        'type' => 'write',
        'cli_path' => 'marketplaces/shopify/scripts/apply_variant_google_shopping.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'output_files' => [],
        'params' => [
            [
                'name' => 'apply',
                'flag' => '--apply',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to Shopify. Omit for a dry-run.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Cap how many products to scan.',
            ],
        ],
    ],
    [
        'slug' => 'shopify.apply-google-shopping',
        'category' => 'gtin-mpn',
        'title' => 'Apply Google Shopping (live write)',
        'description' => 'Writes product-level google_product_category — the one Google Shopping field that\'s genuinely product-level, not variant-level.',
        'usage_notes' => 'Standalone — not part of the GTIN/MPN sequence, run any time. Dry-run by default — --apply actually writes.',
        'type' => 'write',
        'cli_path' => 'marketplaces/shopify/scripts/apply_google_shopping.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'output_files' => ['marketplaces/shopify/data/output/google_shopping_applied.csv'],
        'creates' => [
            [
                'file' => 'google_shopping_applied.csv',
                'columns' => ['numeric_id', 'title', 'changes'],
            ],
        ],
        'params' => [
            [
                'name' => 'apply',
                'flag' => '--apply',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to Shopify. Omit for a dry-run.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Process only the first N products.',
            ],
            [
                'name' => 'ids',
                'flag' => '--ids',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated product IDs to process instead.',
            ],
        ],
    ],
    [
        'slug' => 'shopify.apply-image-alts',
        'category' => 'accessibility',
        'title' => 'Apply Image Alts (live write)',
        'description' => 'Writes authored alt text for featured product images from data/drafts/image_alts.json — the accessibility-sweep counterpart to Apply Metadata\'s image-alt field.',
        'usage_notes' => 'Dry-run by default — --apply actually writes.',
        'type' => 'write',
        'cli_path' => 'marketplaces/shopify/scripts/apply_image_alts.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'output_files' => ['marketplaces/shopify/data/output/image_alts_applied.csv'],
        'creates' => [
            [
                'file' => 'image_alts_applied.csv',
                'columns' => ['media_id', 'alt'],
            ],
        ],
        'params' => [
            [
                'name' => 'apply',
                'flag' => '--apply',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to Shopify. Omit for a dry-run.',
            ],
            [
                'name' => 'limit',
                'flag' => '--limit',
                'type' => 'int',
                'required' => false,
                'help' => 'Process only the first N.',
            ],
            [
                'name' => 'ids',
                'flag' => '--ids',
                'type' => 'string',
                'required' => false,
                'help' => 'Comma-separated media GIDs to process instead.',
            ],
        ],
    ],
    [
        'slug' => 'shopify.apply-blog-image-alts',
        'category' => 'accessibility',
        'title' => 'Apply Blog Image Alts (live write)',
        'description' => 'Fills missing alt text on <img> tags inside blog article bodies.',
        'usage_notes' => 'Dry-run by default — --apply actually writes. Full sweep every run, no limit/ids flags.',
        'type' => 'write',
        'cli_path' => 'marketplaces/shopify/scripts/apply_blog_image_alts.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'output_files' => [],
        'params' => [
            [
                'name' => 'apply',
                'flag' => '--apply',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to Shopify. Omit for a dry-run.',
            ],
        ],
    ],
    [
        'slug' => 'shopify.apply-product-desc-image-alts',
        'category' => 'accessibility',
        'title' => 'Apply Product Description Image Alts (live write)',
        'description' => 'Fills missing alt text on <img> tags inside product description HTML. Idempotent — only touches images with no alt or alt="".',
        'usage_notes' => 'Dry-run by default — --apply actually writes. Full sweep every run, no limit/ids flags.',
        'type' => 'write',
        'cli_path' => 'marketplaces/shopify/scripts/apply_product_desc_image_alts.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'output_files' => [],
        'params' => [
            [
                'name' => 'apply',
                'flag' => '--apply',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to Shopify. Omit for a dry-run.',
            ],
        ],
    ],
    [
        'slug' => 'shopify.apply-product-video-alts',
        'category' => 'accessibility',
        'title' => 'Apply Product Video Alts (live write)',
        'description' => 'Fills missing alt text on product VIDEO/EXTERNAL_VIDEO media. Idempotent — only touches video media with an empty alt.',
        'usage_notes' => 'Dry-run by default — --apply actually writes. Full sweep every run, no limit/ids flags.',
        'type' => 'write',
        'cli_path' => 'marketplaces/shopify/scripts/apply_product_video_alts.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'output_files' => [],
        'params' => [
            [
                'name' => 'apply',
                'flag' => '--apply',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to Shopify. Omit for a dry-run.',
            ],
        ],
    ],
    [
        'slug' => 'shopify.apply-nav-tags',
        'category' => 'nav-taxonomy',
        'title' => 'Apply Nav Tags (live write)',
        'description' => 'Applies nav-* tags to products so Smart collections can drive multi-child nav menus.',
        'usage_notes' => 'Dry-run by default — --apply actually writes (needs write_products scope). --only limits to one nav parent.',
        'type' => 'write',
        'cli_path' => 'marketplaces/shopify/scripts/apply_nav_tags.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'output_files' => [],
        'params' => [
            [
                'name' => 'apply',
                'flag' => '--apply',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to Shopify. Omit for a dry-run.',
            ],
            [
                'name' => 'only',
                'flag' => '--only',
                'type' => 'string',
                'required' => false,
                'help' => 'One nav parent (e.g. nav-rock-hounding) to limit to. Leave blank for all.',
            ],
        ],
    ],
    [
        'slug' => 'shopify.analyze-gsc',
        'category' => 'gsc-ctr',
        'title' => 'Analyze GSC',
        'description' => 'Analyzes a Google Search Console export bundle to find CTR-opportunity and ranking-opportunity worklists — pages/queries ranking well but under-clicked (a title/meta fix) vs. page-2 queries with impressions (a ranking push).',
        'usage_notes' => 'Requires the GSC export bundle (Chart.csv, Countries.csv, Devices.csv, Pages.csv, Queries.csv, Search appearance.csv, Filters.csv) already placed in marketplaces/shopify/data/output/ — export these from the Google Search Console UI yourself first, there\'s no automated pull. No flags.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/analyze_gsc.py',
        'interpreter' => 'python3',
        'featured' => false,
        'output_files' => [
            'marketplaces/shopify/data/output/ctr_opportunity_pages.csv',
            'marketplaces/shopify/data/output/ctr_opportunity_queries.csv',
            'marketplaces/shopify/data/output/ranking_opportunity_queries.csv',
        ],
        'creates' => [
            [
                'file' => 'ctr_opportunity_pages.csv',
                'columns' => ['url', 'page_type', 'clicks', 'impr', 'actual_ctr', 'expected_ctr', 'pos', 'opportunity_clicks'],
            ],
            [
                'file' => 'ctr_opportunity_queries.csv',
                'columns' => ['query', 'clicks', 'impr', 'actual_ctr', 'expected_ctr', 'pos', 'opportunity_clicks'],
            ],
            [
                'file' => 'ranking_opportunity_queries.csv',
                'columns' => ['query', 'clicks', 'impr', 'actual_ctr', 'pos'],
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'shopify.count-review-coverage',
        'category' => 'review-qa',
        'title' => 'Count Review Coverage',
        'description' => 'Counts active products with vs. without a reviews.rating_count value.',
        'usage_notes' => 'Read-only, console report only — no output file. No flags.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/count_review_coverage.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'output_files' => [],
        'params' => [],
    ],
    [
        'slug' => 'shopify.export-review-csv',
        'category' => 'review-qa',
        'title' => 'Export Review CSV',
        'description' => 'Per-variant CSV of every SEO/Google-Shopping field, straight from the live store — a full current-state export independent of the review workflow.',
        'usage_notes' => 'Read-only. No flags.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/export_review_csv.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'output_files' => ['marketplaces/shopify/data/output/seo_review_live.csv'],
        'creates' => [
            [
                'file' => 'seo_review_live.csv',
                'columns' => [
                    'handle', 'product_title', 'variant_title', 'sku', 'gtin_barcode', 'mpn',
                    'seo_title', 'seo_description', 'gpc', 'gender', 'age_group', 'condition',
                    'size_system', 'size_type',
                ],
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'shopify.audit-product-media',
        'category' => 'video-seo',
        'title' => 'Audit Product Media',
        'description' => 'Step 1 of Video SEO: scans every product\'s media for self-hosted video vs. YouTube embed.',
        'usage_notes' => 'Read-only. No flags.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/audit_product_media.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 1,
        'output_files' => ['marketplaces/shopify/data/output/product_video_inventory.csv'],
        'creates' => [
            [
                'file' => 'product_video_inventory.csv',
                'columns' => [
                    'handle', 'title', 'has_hosted_video', 'has_external_video',
                    'has_videoobject_markup', 'hosted_video_url', 'hosted_preview',
                    'hosted_duration_ms', 'external_host', 'external_url', 'video_alt', 'url',
                ],
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'shopify.audit-blog-media',
        'category' => 'video-seo',
        'title' => 'Audit Blog Media',
        'description' => 'Step 1 of Video SEO: the same self-hosted-vs-YouTube video scan for blog article bodies.',
        'usage_notes' => 'Read-only. No flags.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/audit_blog_media.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 1,
        'output_files' => ['marketplaces/shopify/data/output/blog_video_inventory.csv'],
        'creates' => [
            [
                'file' => 'blog_video_inventory.csv',
                'columns' => ['blog', 'article', 'title', 'has_mp4', 'has_youtube', 'video_tag', 'mp4_urls', 'youtube_urls', 'url'],
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'shopify.build-master-video-audit',
        'category' => 'video-seo',
        'title' => 'Build Master Video Audit',
        'description' => 'Step 2 of Video SEO: combines the product/blog video inventories and flags indexability — one row per (URL x video_id), single-video "home" pages (indexable) vs. multi-video pages (only the primary video indexes).',
        'usage_notes' => 'Requires Audit Product Media and Audit Blog Media to have run first. Nothing written to Shopify.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/build_master_video_audit.py',
        'interpreter' => 'python3',
        'featured' => true,
        'step' => 2,
        'output_files' => ['marketplaces/shopify/data/output/master_video_audit.csv'],
        'creates' => [
            [
                'file' => 'master_video_audit.csv',
                'columns' => ['surface', 'url', 'video_id', 'video_title', 'videos_on_page', 'single_video_home', 'in_product_snippet'],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/shopify/data/output/product_video_inventory.csv',
                'label' => 'Produced by Audit Product Media.',
            ],
            [
                'path' => 'marketplaces/shopify/data/output/blog_video_inventory.csv',
                'label' => 'Produced by Audit Blog Media.',
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'shopify.build-video-map',
        'category' => 'video-seo',
        'title' => 'Build Video Map',
        'description' => 'Step 2 of Video SEO: builds a video -> product/collection/blog match proposal, scraping YouTube watch pages for date/duration.',
        'usage_notes' => 'Read-only against Shopify; does fetch real YouTube watch pages over HTTP. No flags.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/build_video_map.py',
        'interpreter' => 'python3',
        'featured' => false,
        'step' => 2,
        'output_files' => ['marketplaces/shopify/data/output/video_product_map.csv'],
        'creates' => [
            [
                'file' => 'video_product_map.csv',
                'columns' => [
                    'video_id', 'video_url', 'embed_url', 'title', 'yt_status', 'upload_date',
                    'duration', 'thumbnail_url', 'kind', 'suggested_target', 'best_product_handle',
                    'best_product_title', 'match_score', 'alt_product_candidates',
                    'suggested_collection', 'CONFIRM_target_handle', 'NOTES',
                ],
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'shopify.build-mp4-worklist',
        'category' => 'video-seo',
        'title' => 'Build MP4 Worklist',
        'description' => 'Step 2 of Video SEO: matches self-hosted MP4 products to their YouTube counterpart — the replacement worklist for de-risking self-hosted video.',
        'usage_notes' => 'No flags.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/build_mp4_worklist.py',
        'interpreter' => 'python3',
        'featured' => false,
        'step' => 2,
        'output_files' => ['marketplaces/shopify/data/output/mp4_replacement_worklist.csv'],
        'creates' => [
            [
                'file' => 'mp4_replacement_worklist.csv',
                'columns' => [
                    'product_title', 'product_page_url', 'shopify_admin', 'current_mp4_seconds',
                    'current_mp4_url', 'replace_with_youtube_url', 'replace_with_youtube_title',
                    'match_confidence', 'notes',
                ],
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'shopify.list-product-videos',
        'category' => 'video-seo',
        'title' => 'List Product Videos',
        'description' => 'Step 3 of Video SEO: enumerates every EXTERNAL_VIDEO on products with a resolvable YouTube ID — the seed list Pull YouTube Meta reads.',
        'usage_notes' => 'Read-only. No flags.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/list_product_videos.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 3,
        'output_files' => ['marketplaces/shopify/data/drafts/video_master_list.csv'],
        'creates' => [
            [
                'file' => 'video_master_list.csv',
                'columns' => ['youtube_id', 'watch_url', 'on_products'],
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'shopify.pull-youtube-meta',
        'category' => 'video-seo',
        'title' => 'Pull YouTube Meta',
        'description' => 'Step 4 of Video SEO: pulls title/description/upload date/duration from the YouTube Data API v3 for every video List Product Videos found.',
        'usage_notes' => 'Requires YOUTUBE_API_KEY in .env. Read-only against Shopify.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/pull_youtube_meta.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 4,
        'output_files' => [
            'marketplaces/shopify/data/drafts/video_metadata.json',
            'marketplaces/shopify/data/drafts/video_metadata.csv',
        ],
        'creates' => [
            [
                'file' => 'video_metadata.csv',
                'columns' => ['youtube_id', 'title', 'upload_date', 'length', 'duration_iso', 'description(first 120)', 'on_products'],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/shopify/data/drafts/video_master_list.csv',
                'label' => 'Produced by List Product Videos.',
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'shopify.build-video-review-csv',
        'category' => 'video-seo',
        'title' => 'Build Video Review CSV',
        'description' => 'Step 5 of Video SEO: merges hand-authored watch-page copy with the pulled YouTube metadata, flagging meta_title/meta_description length issues (>60 / >165 chars).',
        'usage_notes' => 'Requires data/drafts/video_watch_pages_authored.json to already exist — that\'s hand-authored watch-page copy, not produced by any script in this pipeline; author it yourself before running this.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/build_video_review_csv.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'step' => 5,
        'output_files' => ['marketplaces/shopify/data/drafts/video_watch_pages_review.csv'],
        'creates' => [
            [
                'file' => 'video_watch_pages_review.csv',
                'columns' => [
                    '#', 'youtube_id', 'watch_page_title', 'handle', 'mt_len', 'md_len', 'flags',
                    'meta_title', 'meta_description', 'on_page_body', 'upload_date', 'duration_iso', 'length',
                ],
            ],
        ],
        'reference_files' => [
            [
                'path' => 'marketplaces/shopify/data/drafts/video_metadata.json',
                'label' => 'Produced by Pull YouTube Meta.',
            ],
        ],
        'params' => [],
    ],
    [
        'slug' => 'shopify.build-video-watch-pages',
        'category' => 'video-seo',
        'title' => 'Build Video Watch Pages (live write)',
        'description' => 'Step 6 of Video SEO: writes to Shopify — builds a "Videos" blog hub plus one watch-page article per video.',
        'usage_notes' => 'Dry-run by default — --apply actually writes.',
        'type' => 'write',
        'cli_path' => 'marketplaces/shopify/scripts/build_video_watch_pages.php',
        'interpreter' => 'php8.2',
        'featured' => true,
        'step' => 6,
        'output_files' => ['marketplaces/shopify/data/drafts/video_build_preview.csv'],
        'creates' => [
            [
                'file' => 'video_build_preview.csv',
                'columns' => ['action', 'handle', 'title', 'youtube_id', 'upload_date', 'duration', 'featured_image'],
            ],
        ],
        'params' => [
            [
                'name' => 'apply',
                'flag' => '--apply',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to Shopify. Omit for a dry-run.',
            ],
        ],
    ],
    [
        'slug' => 'shopify.apply-video-viewcounts',
        'category' => 'video-seo',
        'title' => 'Apply Video View Counts (live write)',
        'description' => 'Rerunnable maintenance: pulls real YouTube view counts into each watch-page article\'s custom.view_count metafield.',
        'usage_notes' => 'Standalone — not part of the build sequence, safe to rerun any time to refresh view counts. Requires YOUTUBE_API_KEY. Dry-run by default — --apply actually writes.',
        'type' => 'write',
        'cli_path' => 'marketplaces/shopify/scripts/apply_video_viewcounts.php',
        'interpreter' => 'php8.2',
        'featured' => false,
        'output_files' => [],
        'params' => [
            [
                'name' => 'apply',
                'flag' => '--apply',
                'type' => 'bool',
                'required' => false,
                'default' => false,
                'help' => 'Actually write live to Shopify. Omit for a dry-run.',
            ],
        ],
    ],
    [
        'slug' => 'shopify.verify-videoobject-live',
        'category' => 'video-seo',
        'title' => 'Verify VideoObject Live',
        'description' => 'Fetches live product pages and validates the deployed VideoObject JSON-LD — a VideoObject is present, embedUrl/thumbnailUrl point at the expected video, uploadDate/duration are present and correct.',
        'usage_notes' => 'Standalone verification, read-only against the public storefront. Run any time after Build Video Watch Pages to confirm it actually took.',
        'type' => 'read',
        'cli_path' => 'marketplaces/shopify/scripts/verify_videoobject_live.py',
        'interpreter' => 'python3',
        'featured' => false,
        'output_files' => ['marketplaces/shopify/data/output/videoobject_live_check.csv'],
        'creates' => [
            [
                'file' => 'videoobject_live_check.csv',
                'columns' => ['url', 'expected_vid', 'status', 'got_vid', 'uploadDate', 'duration', 'n_videoobjects', 'detail'],
            ],
        ],
        'params' => [],
    ],
];
